# Generated by Django 4.1.3 on 2022-11-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='buy_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
